name = "Yakari Demo"

# High-level configuration applied to every menu
[configuration]
# Toggles to sort arguments, command, and menus by alphabetical order.
# Default to true.
sort_arguments = false
# sort_commands = true
# sort_menus = true

[configuration.named_arguments_style]
# The way to represent named argument and multi-valued named argument is
# different from one CLI to the next. This section lets you update the style so
# Yakari matches your target CLI.

separator = "equal"    # MUST be one of "equal" or "space"
multi_style = "repeat" # MUST be "repeat" or a single character like " " or ","

# You can optionally define parent arguments that will be automatically
# used in lower-level menus.
[arguments.-p]
name = "--parent"
value = "100"

# Showcase the different types of arguments supported by Yakari
[menus.a]
name = "Arguments showcase"

[menus.a.arguments.-f]
flag = "--flag"
description = "On/off argument (flag)."

[menus.a.arguments.-n]
name = "--named"
description = "Named argument with arbitrary value."

[menus.a.arguments.-d]
name = "--named-with-default"
value = "3"
description = "Named argument with arbitrary value and a default."

[menus.a.arguments.--mn]
name = "--multi-named"
multi = true
suggestions = { values = ["banana", "apple", "peach"] }
description = "Named argument with multiple arbitrary values and hard-coded suggestions."

[menus.a.arguments.--ds]
name = "--dynamic-suggestion"
description = "Named argument with dynamic suggestions."
suggestions = { command = "ls -1" }

[menus.a.arguments.-c]
name = "--single-choice"
description = "Single choice named argument."
choices = ["python", "rust", "dotnet", "typescript"]

[menus.a.arguments.--mc]
name = "--multi-choice"
description = "Multiple choice named argument."
multi = true
choices = ["jazz", "blues", "npr news"]

[menus.a.arguments.--pwd]
name = "--password"
description = "Password-like argument (obfuscated)."
password = true

[menus.a.commands.d]
name = "display"
description = "Echo all the defined arguments"
template = ["echo", { include = "*" }]


# Showcase ways to define commands with Yakari
[menus.c]
name = "Commands showcase"
configuration.sort_commands = false

[menus.c.arguments.-f]
flag = "--flag"
on = true
description = "On/off argument (flag)."

[menus.c.arguments.-n]
name = "--named"
value = "zidane"
description = "Named argument with arbitrary value."

[menus.c.commands.a]
name = "all"
description = "Command that uses *all* the arguments defined in the menu"
template = ["echo", { include = "*" }]

[menus.c.commands.e]
name = "exclude"
description = "Command that excludes some arguments."
template = ["echo", { include = "*", exclude = ["-p", "-f"] }]

[menus.c.commands.i]
name = "include"
description = "Command that includes a specific list of arguments."
template = ["echo", { include = ["-f", "-n"] }]

[menus.c.commands.d]
name = "dynamic"
description = "Command that prompt the user for dynamic arguments"
template = [
  "echo",
  { name = "-m" },
  { name = "-E", value = [
    "banana",
    "apple",
  ], multi = true },
]
